### ISSUE TITLE
Blocking ipn calls

### ISSUE THREAD

**Issue by lrkwz** [jreinke/magento-require-login#2]
I think this extension should not block ipn calls (i.e. paypal calling http://<shop_host>/<path>/paypal/ipn/).

**Comment by lrkwz** [comment]
Ok well this can be achieved using the Require Login Whitelist reg expr ... I've added |(paypal/\ipn) to the default one and it seems ok.

**Comment by jreinke** [comment]
Fixed from c9d9218

Thank you
